[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[deploy.variables]]
name = "WHATSAPP_SOURCE_GROUPS"
description = "Comma-separated list of group names to scan for links"
value = "Sling. Ship. Grow"

[[deploy.variables]]
name = "WHATSAPP_FORWARD_RECIPIENT"
description = "Group name or phone number to forward links to"
value = "בני אוהב את עצמו"

[[deploy.variables]]
name = "WHATSAPP_BRIDGE_WAIT_TIME"
description = "Minutes to wait for bridge sync before running forwarder"
value = "2"

[deploy.volumes]
"/app/persistent" = "whatsapp-data" 